typography_spectrum: 0.6148572040256113
color:
  brandStrength: 0.8551950245164335
  lightness: 0.3186333042103797
  saturation: 0.9317906275391579
  rhythmicContrast: 0.044170327950268984
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.2083446611650288
name: Sahara Commodities
title: Serial Entrepreneurs
